baseURL = ""
languageCode = "zh-CN"
title = "米司导航"
theme = "startpage"

copyright = "米司特包"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

# [permalinks]
#     posts = "/:year/:month/:slug/"
#     post = "/:year/:month/:slug/"
#     pages = "/:slug/"
#     page = "/:slug/"

[Author]  
  name = "米司特包"

[params]
welcomeText = "米司导航"
startPageColumns = true
description = "米司导航"

  [[params.searchEngines]]
  name = "谷歌搜索"
  activated = true
  url = "https://www.google.com/search"

  [[params.searchEngines]]
  name = "必应搜索"
  activated = true
  url = "https://www.bing.com/search"

  [[params.searchEngines]]
  name = "百度搜索"
  activated = true
  url = "https://baidu.com/s"
